<?php
/**
 * @category    Tukish
 * @package     Tukish_CmsHierarchy
 * @version     1.2.1
 * @copyright   Copyright (c) 2014 Tukish inc
 */

/**
 * @var $this Tukish_CmsHierarchy_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="box">
    <div style="background:url('http://i.imgur.com/NtYmWIh.png') no-repeat left center;padding-left:55px;min-height:42px;">
        <h4><?php echo $this->helper('tukish_cmshierarchy')->__('Tukish CmsHierarchy allows you to manage CMS pages as a tree structure.'); ?></h4>
        <p><?php echo $this->helper('tukish_cmshierarchy')->__('Supports pages permissions, drag & drop, 301 redirects, shared pages and frontend navigation.'); ?></p>
    </div>
</div>