<?php if (count($this->getProducts()) > 0):?>
<?php $_helper = $this->helper('catalog/output'); ?>
    <div class="jcarousel-wrapper">
        <div class="home-page-products-header">
            <span><?php echo $this->__('We recommend'); ?></span>
        </div>
        <div class="jcarousel">
            <ul>
            <?php foreach ($this->getProducts() as $_product): ?>
                <li class="jcarousel-product-item">
                    <?php // Product Image ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                        <?php /* Based on the native RWD styling, product images are displayed at a max of ~400px wide when viewed on a
                        one column page layout with four product columns from a 1280px viewport. For bandwidth reasons,
                        we are going to serve a 300px image, as it will look fine at 400px and most of the times, the image
                        will be displayed at a smaller size (eg, if two column are being used or viewport is smaller than 1280px).
                        This $_imgSize value could even be decreased further, based on the page layout
                        (one column, two column, three column) and number of product columns. */ ?>
                        <?php $_imgSize = 210; ?>
                        <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                             src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>" />
                    </a>
                    <?php // Product description ?>
                    <div class="product-shop">
                        <div class="f-fix">
                            <div class="product-primary">
                                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                            </div>
                            <div class="product-secondary">
                                <?php echo $this->getPriceHtml($_product, true) ?>
                            </div>
                            <?php if (!$this->isAddToCartDisabled()): ?>
                            <div class="product-secondary">
                                <?php if($_product->isSaleable() && !$_product->canConfigure()): ?>
                                    <p class="action"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                                <?php elseif($_product->isSaleable()): ?>
                                    <p class="action"><a title="<?php echo $this->__('View Details') ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a></p>
                                <?php else: ?>
                                    <p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                            </div>
                            <?php endif; ?>
                    </div>

                </li>
            <?php endforeach; ?>
            </ul>
        </div>

        <a href="#" class="jcarousel-control-prev">&lsaquo;</a>
        <a href="#" class="jcarousel-control-next">&rsaquo;</a>
    </div>
<?php endif; ?>
