<?php
/**
 * @category    Tukish
 * @package     Tukish_CmsHierarchy
 * @version     1.2.1
 * @copyright   Copyright (c) 2014 Tukish inc
 */
?>
<?php
/**
 * @see Tukish_CmsHierarchy_Block_Adminhtml_Cms_Page_Edit
 * @var $this Tukish_CmsHierarchy_Block_Adminhtml_Cms_Page_Edit
 */
 ?>
<?php echo $this->getFormInitScripts() ?>
<div class="content-header">
    <?php echo $this->getHeaderHtml() ?>
    <p class="form-buttons"><?php echo $this->getButtonsHtml('header') ?></p>
</div>
<?php echo $this->getTabsHtml(); ?>
<?php echo $this->getFormHtml() ?>
<?php if ($this->hasFooterButtons()): ?>
    <div class="content-footer">
        <p class="form-buttons"><?php echo $this->getButtonsHtml('footer') ?></p>
    </div>
<?php endif; ?>
<script type="text/javascript">
    editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl() ?>');
</script>
<?php echo $this->getFormScripts() ?>
